// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD613u0BTTd8ssNYf8JDL4uETbgUFDXsvI',
    appId: '1:777340799230:web:0a37211c85d6ea30d5bdaf',
    messagingSenderId: '777340799230',
    projectId: 'onlinechantha',
    authDomain: 'onlinechantha.firebaseapp.com',
    storageBucket: 'onlinechantha.firebasestorage.app',
    measurementId: 'G-MVH5E4KWNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3U_72MplLO7aBO6HHrZAaf9Ikt4qacl4',
    appId: '1:777340799230:android:cee57c700be0eda8d5bdaf',
    messagingSenderId: '777340799230',
    projectId: 'onlinechantha',
    storageBucket: 'onlinechantha.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWgqc7no5bmZrHRuoGSwu_mZhrZ-wIU1o',
    appId: '1:777340799230:ios:d8a0f12f2f146b85d5bdaf',
    messagingSenderId: '777340799230',
    projectId: 'onlinechantha',
    storageBucket: 'onlinechantha.firebasestorage.app',
    iosBundleId: 'com.example.mobileShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWgqc7no5bmZrHRuoGSwu_mZhrZ-wIU1o',
    appId: '1:777340799230:ios:d8a0f12f2f146b85d5bdaf',
    messagingSenderId: '777340799230',
    projectId: 'onlinechantha',
    storageBucket: 'onlinechantha.firebasestorage.app',
    iosBundleId: 'com.example.mobileShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD613u0BTTd8ssNYf8JDL4uETbgUFDXsvI',
    appId: '1:777340799230:web:d984eb3b2580bbaad5bdaf',
    messagingSenderId: '777340799230',
    projectId: 'onlinechantha',
    authDomain: 'onlinechantha.firebaseapp.com',
    storageBucket: 'onlinechantha.firebasestorage.app',
    measurementId: 'G-DXNS0WSX9W',
  );
}
